"""Pipeline utilities for data loading and vectorized operations."""
from src.pipeline.utils.duckdb_reader import DuckDBReader
from src.pipeline.utils.vectorized_ops import (
    LevelInfo,
    build_ohlcv_vectorized,
    compute_atr_vectorized,
    futures_trades_from_df,
    mbp10_from_df,
    generate_level_universe_vectorized,
    compute_dynamic_level_series,
    detect_touches_vectorized,
    detect_dynamic_level_touches,
    compute_physics_batch,
    compute_approach_context_vectorized,
    compute_structural_distances,
    compute_mean_reversion_features,
    compute_confluence_features_dynamic,
    compute_confluence_alignment,
    compute_dealer_velocity_features,
    compute_pressure_indicators,
    add_sparse_feature_transforms,
    add_normalized_features,
    compute_attempt_features,
    compute_confluence_level_features,
    label_outcomes_vectorized,
)

__all__ = [
    "DuckDBReader",
    "LevelInfo",
    "build_ohlcv_vectorized",
    "compute_atr_vectorized",
    "futures_trades_from_df",
    "mbp10_from_df",
    "generate_level_universe_vectorized",
    "compute_dynamic_level_series",
    "detect_touches_vectorized",
    "detect_dynamic_level_touches",
    "compute_physics_batch",
    "compute_approach_context_vectorized",
    "compute_structural_distances",
    "compute_mean_reversion_features",
    "compute_confluence_features_dynamic",
    "compute_confluence_alignment",
    "compute_dealer_velocity_features",
    "compute_pressure_indicators",
    "add_sparse_feature_transforms",
    "add_normalized_features",
    "compute_attempt_features",
    "compute_confluence_level_features",
    "label_outcomes_vectorized",
]
