"""
Central Source of Truth for Pipeline Feature Definitions.

This module defines the canonical lists of features generated by each stage of the pipeline.
Use these constants to validate schema integrity and track feature provenance.
"""

from typing import List, Set

# ==============================================================================
# Stage 0: Base Features (Identity + Market State)
# ==============================================================================

IDENTITY_FEATURES: List[str] = [
    'event_id',
    'ts_ns',
    'timestamp',
    'date',
]

MARKET_STATE_FEATURES: List[str] = [
    'spot',
    'atr',
    'volatility',
    'minutes_since_open',
    'bars_since_open',
    'or_active',  # Opening Range active flag
]

# Computed in Stage 1-2 usually, but part of "Base" context for interaction
BASE_FEATURES: List[str] = IDENTITY_FEATURES + MARKET_STATE_FEATURES

# ==============================================================================
# Stage Deltas (Level-Based / ES Pipeline)
# ==============================================================================

# Stage 5: Compute Physics (Instantaneous)
LEVEL_PHYSICS_FEATURES: List[str] = [
    # Barrier State
    'barrier_state',
    'barrier_size',
    'barrier_dist',
    'barrier_dist_atr',
    # Futures Active Flow (Tape) - Spatial
    'tape_velocity',
    'tape_buy_vol',
    'tape_sell_vol',
    'tape_imbalance',
    'tape_buy_vol_above',
    'tape_sell_vol_above',
    'tape_imbalance_above',
    'tape_buy_vol_below',
    'tape_sell_vol_below',
    'tape_imbalance_below',
    
    # Futures Resting Liquidity (Depth) - Spatial
    'limit_bid_size',
    'limit_ask_size',
    'limit_bid_size_above',
    'limit_ask_size_above',
    'limit_bid_size_below',
    'limit_ask_size_below',

    # Options Active Flow (Tide) - Spatial
    'call_tide',
    'put_tide',
    'call_tide_above',
    'put_tide_above',
    'call_tide_below',
    'put_tide_below',
    
    # State Summaries
    'barrier_state',
    'fuel_level',
    'fuel_effect',
]

# Stage 6: Compue Kinematics
KINEMATICS_FEATURES: List[str] = [
    # Windows: 1min, 5min, 15min typically
    # For EACH window w:
    # 'velocity_w', 'acceleration_w', 'jerk_w', 'velocity_w_signed', ...
]

def get_kinematics_features(windows: List[str]) -> List[str]:
    features = []
    for w in windows:
        features.extend([
            f'velocity_{w}',
            f'acceleration_{w}',
            f'jerk_{w}',
            f'displacement_{w}',
        ])
    return features

# Stage 7: Compute OFI
OFI_FEATURES: List[str] = [
    # Windows: 1min, 5min, etc.
]

def get_ofi_features(windows: List[str]) -> List[str]:
    features = []
    for w in windows:
        features.append(f'ofi_{w}')
    features.append('ofi_acceleration')
    return features

# Stage 8: Compute Microstructure
MICROSTRUCTURE_FEATURES: List[str] = [
    'vacuum_imbalance',
    'vacuum_gap',
    'latency_proxy',
    'latency_spike',
    'spread',          # Level-relative or spot
    'depth_imbalance', # Level-relative or spot
]

# Stage 9: Compute Barrier Evolution
BARRIER_EVOLUTION_FEATURES: List[str] = [
    'barrier_delta_1min',
    'barrier_delta_5min',
    'barrier_trend',
]

# Stage 10: Compute Level Distances
LEVEL_DISTANCE_FEATURES: List[str] = [
    'dist_to_pm_high',
    'dist_to_pm_low',
    'dist_to_or_high',
    'dist_to_or_low',
    'dist_to_vwap',
]

# Stage 11: Compute GEX Features
GEX_FEATURES: List[str] = [
    'gex_profile_gamma',
    'gex_profile_speed',
    'gex_profile_acceleration',
    'gex_asymmetry',
]

# Stage 12: Compute Level Liquidity (Order Book & Gamma)
LEVEL_LIQUIDITY_FEATURES: List[str] = [
    # Order Book Liquidity (Limit Orders)
    'ob_bid_price',
    'ob_ask_price',
    'ob_bid_dist',
    'ob_ask_dist',
    'ob_bid_size',
    'ob_ask_size',
    # Gamma Positioning (Dealer Inventory)
    'gamma_call_level_dist',
    'gamma_put_level_dist',
]

# Stage 13: Compute Force/Mass
FORCE_MASS_FEATURES: List[str] = [
    'force_proxy',
    'mass_proxy',
    'force_mass_ratio',
    'predicted_accel',
    'accel_residual',
    'flow_alignment',
]

# Stage 14: Compute Approach
APPROACH_FEATURES: List[str] = [
    'approach_velocity',
    'approach_bars',
    'approach_distance',
    'attempt_index',
    'attempt_cluster_id',
]

# Stage 15: Label Outcomes
OUTCOME_LABELS: List[str] = [
    'outcome_2min',
    'outcome_4min',
    'outcome_8min',
    'excursion_favorable',
    'excursion_adverse',
    'strength_signed',
]

# ==============================================================================
# Global Features (Market-Wide)
# ==============================================================================

GLOBAL_OPTIONS_FEATURES: List[str] = [
    'total_gex',
    'total_call_gex',
    'total_put_gex',
    'gex_asymmetry',
    'call_tide',
    'put_tide',
    'total_call_volume',
    'total_put_volume',
    'put_call_ratio',
]

GLOBAL_OFI_FEATURES: List[str] = [
    'ofi_30s',
    'ofi_60s',
    'ofi_120s',
    'ofi_300s',
    'ofi_acceleration',
]

GLOBAL_KINEMATICS_FEATURES: List[str] = [
    'velocity_1min', 'velocity_1min_abs', 'acceleration_1min', 'jerk_1min',
    'velocity_5min', 'velocity_5min_abs', 'acceleration_5min', 'jerk_5min',
    # Add other windows as needed
]

GLOBAL_MICRO_FEATURES: List[str] = [
    'spread',
    'spread_pct',
    'bid_depth',
    'ask_depth',
    'depth_imbalance',
    'mid_price',
]

MARKET_LIQUIDITY_FEATURES: List[str] = [
    # Order Book (Global)
    'futures_bid_limit_price', 'futures_ask_limit_price',
    'futures_bid_limit_dist', 'futures_ask_limit_dist',
    # Gamma (Global)
    'options_call_gamma_price', 'options_put_gamma_price',
    'options_call_gamma_dist', 'options_put_gamma_dist',
]
