$schema: https://azuremlschemas.azureedge.net/latest/sweepJob.schema.json
type: sweep
name: train_hyperopt_sweep_run
display_name: train_hyperopt_sweep_run
experiment_name: spymaster_hyperopt
compute: azureml:cpu-cluster
sampling_algorithm:
  type: random
  seed: 42
search_space:
  max_evals:
    type: choice
    values: [5, 10]
objective:
  goal: maximize
  primary_metric: val_accuracy
limits:
  max_total_trials: 2
  max_concurrent_trials: 1
trial:
  code: ../../../backend/src
  command: >-
    python ml/train_hyperopt.py
    --train_dir ${{inputs.train_dir}}
    --val_dir ${{inputs.val_dir}}
    --test_dir ${{inputs.test_dir}}
    --max_evals ${{search_space.max_evals}}
    --model_out ${{outputs.model_out}}
  environment: azureml:spymaster-hyperopt:2
inputs:
  train_dir:
    type: uri_folder
    path: azureml://datastores/ml_artifacts/paths/datasets/ES_MODEL/2025-10-01/splits/train/
  val_dir:
    type: uri_folder
    path: azureml://datastores/ml_artifacts/paths/datasets/ES_MODEL/2025-10-01/splits/val/
  test_dir:
    type: uri_folder
    path: azureml://datastores/ml_artifacts/paths/datasets/ES_MODEL/2025-10-01/splits/test/
outputs:
  model_out:
    type: uri_file
